github.com:
    users:
        nurmuhammedjoy:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: nurmuhammedjoy
